feat: bundle size report to DD

diff --git a/.github/actions/analyze/action.yml b/.github/actions/analyze/action.yml
--- a/.github/actions/analyze/action.yml
+++ b/.github/actions/analyze/action.yml
@@ -63,6 +63,9 @@ inputs:
   TRUSTPILOT_API_KEY:
     description: 'Trustpilot api key'
     required: false
+  BUNDLE_SIZE_TOKEN:
+    description: 'Datadog API key for bundle size'
+    required: true
 
 runs:
   using: composite
@@ -132,11 +135,14 @@ runs:
     shell: bash
     run: |
       DIFF_OUTPUT_HTML=$(node .github/actions/analyze/compareReports.js --format=html)
+      PACKAGE_SIZES=$(node .github/actions/analyze/compareReports.js --format=json | jq -c .)
       ABOVE_THRESHOLD=$(node .github/actions/analyze/compareReports.js --format=boolean) || { echo "Threshold check failed"; exit 1; }
 
       # Output results to GITHUB_OUTPUT
       echo "diff_output_html=$DIFF_OUTPUT_HTML" >> $GITHUB_OUTPUT
+      echo "package_sizes=$PACKAGE_SIZES" >> $GITHUB_OUTPUT
       echo "above_threshold=$ABOVE_THRESHOLD" >> $GITHUB_OUTPUT
+
 
   - name: Comment on PR with Diff Output
     if: steps.get_artifact_url.outputs.artifact_url != 'null' && inputs.ISSUE_NUMBER
@@ -197,3 +203,49 @@ runs:
       name: analyse-${{ env.SANITIZED_REF_NAME }}
       path: analyse.zip
       retention-days: 5
+
+  - name: Send package sizes to Datadog
+    shell: bash
+    run: |
+      PACKAGE_SIZES=$(echo '${{ steps.diff.outputs.package_sizes }}' | jq -c .)
+      BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
+      
+      BUNDLE_SIZE_TOKEN="${{ inputs.BUNDLE_SIZE_TOKEN }}"
+      DATADOG_METRICS_URL="https://api.datadoghq.eu/api/v1/series"
+      
+      # Print out part of the BUNDLE_SIZE_TOKEN to validate its presence
+      echo "BUNDLE_SIZE_TOKEN starts with: ${BUNDLE_SIZE_TOKEN:0:4}... (redacted)"
+      echo "Length of BUNDLE_SIZE_TOKEN: ${#BUNDLE_SIZE_TOKEN}"
+
+      if [ -z "$BUNDLE_SIZE_TOKEN" ]; then
+        echo "Error: BUNDLE_SIZE_TOKEN is not set."
+        exit 1
+      fi
+
+      # Send each package size as a separate metric
+      for row in $(echo "${PACKAGE_SIZES}" | jq -r 'to_entries[] | @base64'); do
+        _jq() {
+          echo ${row} | base64 --decode | jq -r ${1}
+        }
+
+        PACKAGE_NAME=$(_jq '.key')
+        PACKAGE_SIZE=$(_jq '.value.newSize')
+
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-type: application/json" -H "DD-API-KEY: $BUNDLE_SIZE_TOKEN" \
+          -d '{
+                "series": [{
+                  "metric": "deriv-app.package-size.'$PACKAGE_NAME'",
+                  "points": [['$(date +%s)', '$PACKAGE_SIZE']],
+                  "type": "gauge",
+                  "tags": ["env:production", "branch:'$BRANCH_NAME'"]
+                }]
+              }' \
+          $DATADOG_METRICS_URL)
+
+        if [ "$RESPONSE" -ne 202 ]; then
+          echo "Error: Failed to send data to Datadog for package $PACKAGE_NAME. Response code: $RESPONSE"
+          exit 1
+        else
+          echo "Successfully sent data for package $PACKAGE_NAME"
+        fi
+      done
